// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAPBackOffice.Data;

namespace PAPBackOffice.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20210311023754_NewTables20210311")]
    partial class NewTables20210311
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Consultoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoBase")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Consultoria");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.EmpresaConsultoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsultoriaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaConsultoriaEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultoriaId");

                    b.HasIndex("EmpresaConsultoriaEstadoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaConsultoria");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.EmpresaConsultoriaEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmpresaConsultoriaEstado");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<float>("Desconto")
                        .HasColumnType("real");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FaturaEstadoId")
                        .HasColumnType("int");

                    b.Property<float>("IVA")
                        .HasColumnType("real");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FaturaEstadoId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.FaturaEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FaturaEstado");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.FaturaLinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsultoriaId")
                        .HasColumnType("int");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("FaturaLinha");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Data")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoEstadoId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoPrioridadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PedidoEstadoId");

                    b.HasIndex("PedidoOrigemId");

                    b.HasIndex("PedidoPrioridadeId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoComentario");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidoEstado");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoOrigem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidoOrigem");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoPrioridade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidoPrioridade");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Colaborador", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Empresa", "Empresa")
                        .WithMany("Colaborador")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.EmpresaConsultoria", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Consultoria", "Consultoria")
                        .WithMany()
                        .HasForeignKey("ConsultoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.EmpresaConsultoriaEstado", "EmpresaConsultoriaEstado")
                        .WithMany("EmpresaConsultoria")
                        .HasForeignKey("EmpresaConsultoriaEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultoria");

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaConsultoriaEstado");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Fatura", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.FaturaEstado", "FaturaEstado")
                        .WithMany("Fatura")
                        .HasForeignKey("FaturaEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Empresa");

                    b.Navigation("FaturaEstado");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.FaturaLinha", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Fatura", "Fatura")
                        .WithMany("FaturaLinha")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Pedido", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Colaborador", "Colaborador")
                        .WithMany("Pedido")
                        .HasForeignKey("ColaboradorId");

                    b.HasOne("PAPBackOffice.Data.Entities.Empresa", "Empresa")
                        .WithMany("Pedido")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("PAPBackOffice.Data.Entities.PedidoEstado", "PedidoEstado")
                        .WithMany("Pedido")
                        .HasForeignKey("PedidoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.PedidoOrigem", "PedidoOrigem")
                        .WithMany("Pedido")
                        .HasForeignKey("PedidoOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAPBackOffice.Data.Entities.PedidoPrioridade", "PedidoPrioridade")
                        .WithMany("Pedido")
                        .HasForeignKey("PedidoPrioridadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Empresa");

                    b.Navigation("PedidoEstado");

                    b.Navigation("PedidoOrigem");

                    b.Navigation("PedidoPrioridade");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoComentario", b =>
                {
                    b.HasOne("PAPBackOffice.Data.Entities.Pedido", "Pedido")
                        .WithMany("PedidoComentario")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Colaborador", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Empresa", b =>
                {
                    b.Navigation("Colaborador");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.EmpresaConsultoriaEstado", b =>
                {
                    b.Navigation("EmpresaConsultoria");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Fatura", b =>
                {
                    b.Navigation("FaturaLinha");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.FaturaEstado", b =>
                {
                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.Pedido", b =>
                {
                    b.Navigation("PedidoComentario");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoEstado", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoOrigem", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PAPBackOffice.Data.Entities.PedidoPrioridade", b =>
                {
                    b.Navigation("Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
